version: "3.9"

services:

  backend:
    build: ./backend-node
    container_name: iot_backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=iot_user
      - DB_PASSWORD=d13g0f3r
      - DB_NAME=iot_monitoring
    depends_on:
      - database
    networks:
      - iot_net

  simulator:
    build: ./simulator-python
    container_name: iot_simulator
    restart: always
    environment:
      - WS_BACKEND_URL=http://backend:4000
    depends_on:
      - backend
    networks:
      - iot_net

  database:
    image: postgres:15
    container_name: iot_database
    restart: always
    environment:
      - POSTGRES_USER=iot_user
      - POSTGRES_PASSWORD=d13g0f3r
      - POSTGRES_DB=iot_monitoring
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - iot_net
  
  
  frontend:
    build: ./frontend
    container_name: iot_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000/api
      VITE_WS_URL: ws://localhost:4000

networks:
  iot_net:
    driver: bridge

volumes:
  db_data:
